matrix:
  include:
    - name: test_cli
      stage: test
      install:
        # START TESTING THE CLI
        - cd cli
        - pip install pipenv
        - pipenv install --dev
      script:
        - pipenv run pytest
        # END TESTING THE CLI
    - name: test_python_client
      stage: test
      script:
        - onshape-clients -c python install
        - onshape-clients -c python test
    - name: test_go_client
      language: go
      go:
        - 1.14.x
      stage: test
      script:
        - go env
        - onshape-clients setup
        - PATH=$PATH:~/bin/openapitools/
        - make go-test
      env:
        global:
          - GO111MODULE=on
          - GOARCH=amd64
    - name: lint_clients
      stage: test
      script:
        - onshape-clients lint
    - name: deploy_clients
      stage: deploy
      install:
        - onshape-clients setup
        - PATH=$PATH:~/bin/openapitools/
        - onshape-clients -c go generate
        - nvm install 12
        - npm install .
      script:
        - npx semantic-release
stages:
  - test
  - deploy
language: python
python: 3.7
before_install:
  - openssl aes-256-cbc -K $encrypted_823a8aeaad18_key -iv $encrypted_823a8aeaad18_iv
    -in secrets.sh.enc -out secrets.sh -d
  - source environment.sh
